# This workflow will install Python dependencies and run the Flask server using make install and make run
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies with Makefile
      run: |
        make install

    - name: Run Flask server (with sleep)
      run: |
        make run &  # Run the Flask server in the background
        sleep 10    # Sleep for 10 seconds to allow the server to start

